package com.dockyard.java11features.service;

import com.dockyard.java11features.dto.VarInferenceResult;
import com.dockyard.java11features.functional.NonNegative;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.BiFunction;

/**
 * VarService — {@code var} (JEP 286, Java 10) lets the compiler infer a
 * local variable's static type from its initializer, instead of you writing
 * it out. Java 11 (JEP 323) extended this to lambda PARAMETERS specifically
 * so they could carry annotations (a lambda parameter without {@code var}
 * cannot be annotated — you'd have to write out the full type just to attach
 * one).
 *
 * <h2>The most common misconception</h2>
 * {@code var} is NOT dynamic typing, NOT {@code Object}, and NOT "no type."
 * The compiler determines ONE concrete static type at compile time from the
 * right-hand side and bakes it in — {@code var list = new ArrayList<String>()}
 * is exactly as strongly typed as {@code ArrayList<String> list = ...}; the
 * generated bytecode is identical. {@code var} only removes REDUNDANT
 * left-hand-side typing.
 *
 * <h2>Where var can and cannot be used</h2>
 * <ul>
 *   <li>CAN: local variables with an initializer, enhanced for-loop
 *       variables, try-with-resources resource variables, and (Java 11)
 *       lambda parameters (ALL parameters must use {@code var}, not a
 *       mix).</li>
 *   <li>CANNOT: fields, method parameters (outside of lambdas), method
 *       return types, generic type arguments, or a local variable with no
 *       initializer / initialized to {@code null} with no cast, or a lambda
 *       / method reference with no explicit target type (there's nothing
 *       for the compiler to infer FROM).</li>
 * </ul>
 */
@Service
public class VarService {

    /** var infers a concrete type from the initializer — never a "no type" or Object. */
    public List<VarInferenceResult> localVariableInference() {
        var count = 42;                          // inferred: int
        var label = "answer";                    // inferred: java.lang.String
        var numbers = List.of(1, 2, 3);           // inferred: java.util.List<Integer>
        var lookup = Map.of("a", 1, "b", 2);      // inferred: java.util.Map<String,Integer>

        List<VarInferenceResult> results = new ArrayList<>();
        results.add(VarInferenceResult.builder().declaration("var count = 42;").inferredType("int").value(String.valueOf(count)).build());
        results.add(VarInferenceResult.builder().declaration("var label = \"answer\";").inferredType(label.getClass().getName()).value(label).build());
        results.add(VarInferenceResult.builder().declaration("var numbers = List.of(1, 2, 3);").inferredType(numbers.getClass().getInterfaces()[0].getName() + "<Integer>").value(numbers.toString()).build());
        results.add(VarInferenceResult.builder().declaration("var lookup = Map.of(\"a\", 1, \"b\", 2);").inferredType("java.util.Map<String,Integer>").value(lookup.toString()).build());
        return results;
    }

    /** var works in an enhanced for-loop, inferring the element type from the collection's generic type. */
    public List<String> enhancedForLoop() {
        List<String> log = new ArrayList<>();
        var fruits = List.of("apple", "banana", "cherry"); // var List<String>
        for (var fruit : fruits) {                          // 'fruit' is inferred as String
            log.add("Iterating: " + fruit + " (inferred type: java.lang.String)");
        }
        return log;
    }

    /**
     * Java 11, JEP 323 — var is allowed on lambda PARAMETERS, specifically so
     * they can carry annotations. Every parameter must use var consistently
     * (no mixing var and explicit types in the same parameter list).
     */
    public int lambdaParams(int a, int b) {
        // @NonNegative is a TYPE_USE annotation — impossible to attach to a bare,
        // type-less lambda parameter ('x' with no type at all). Before Java 11 you'd
        // have had to spell out the full parameter type just to hang this annotation
        // on it; 'var' lets you keep type INFERENCE while still allowing the annotation.
        BiFunction<Integer, Integer, Integer> sum =
                (@NonNegative var x, @NonNegative var y) -> x + y;
        return sum.apply(a, b);
    }

    /** var also works for try-with-resources resource variables. */
    public String tryWithResourcesDemo() {
        try (var reader = new java.io.BufferedReader(new StringReader("line one\nline two"))) { // var infers BufferedReader
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                sb.append(line).append(" | ");
            }
            return sb.toString();
        } catch (IOException e) {
            throw new IllegalStateException("Unexpected IO failure reading from an in-memory StringReader", e);
        }
    }

    /** var's restrictions — none of these compile, so this documents rather than executes them. */
    public List<String> pitfalls() {
        return List.of(
                "var field;                           // COMPILE ERROR — var cannot be used for a class/instance field",
                "void method(var x) {}                // COMPILE ERROR — var cannot be used for a regular method parameter",
                "var method() { return 1; }           // COMPILE ERROR — var cannot be used as a method return type",
                "var x;                               // COMPILE ERROR — no initializer means nothing to infer from",
                "var x = null;                        // COMPILE ERROR — null has no type to infer (a cast like (String) null would work)",
                "var x = () -> 42;                    // COMPILE ERROR — a lambda has no type of its own to infer; it needs an explicit target type",
                "List<var> list = ...;                // COMPILE ERROR — var cannot be used as a generic type argument",
                "(var x, int y) -> x + y              // COMPILE ERROR — cannot mix var and an explicit type in the same lambda parameter list"
        );
    }

}