package com.dockyard.springdockerapp.service;

import com.dockyard.springdockerapp.entity.Product;
import com.dockyard.springdockerapp.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * ProductService.java — with Redis caching
 *
 * This is the updated version of ProductService from 01-spring-setup.
 * The only difference is the addition of caching annotations.
 *
 * Three caching annotations:
 *
 *   @Cacheable   — check cache first, only call method if not cached
 *                  used on READ operations (get, find)
 *
 *   @CachePut    — always call method AND update the cache with result
 *                  used on UPDATE operations so cache stays in sync
 *
 *   @CacheEvict  — remove entry from cache
 *                  used on DELETE operations so stale data is removed
 *
 * How to prove caching is working:
 *   Call GET /api/products/1 twice
 *   First call: logs show "Fetching product" + Hibernate SQL query
 *   Second call: logs show "Fetching product" but NO Hibernate SQL query
 *   The second call was served from Redis, not the database
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ProductService {

    // Spring injects this automatically via the constructor generated by @RequiredArgsConstructor
    private final ProductRepository productRepository;

    // No caching on getAll — list changes too frequently
    // Caching a list also means the cache gets stale when any product changes
    public List<Product> getAllProducts() {
        log.info("Fetching all products from database");
        return productRepository.findAll();
    }

    // @Cacheable checks Redis first before calling this method
    // cache name is "products"
    // key is the product id — stored in Redis as "products::1"
    // If "products::1" exists in Redis the method body is SKIPPED
    // and the cached value is returned directly
    // If not found in Redis the method runs, result is saved to Redis, then returned
    @Cacheable(value = "products", key = "#id")
    public Optional<Product> getProductById(Long id) {
        log.info("Fetching product with id: {} from database", id);
        // This log line only appears on cache MISS
        // If you see this log the data came from the database
        // If you do NOT see this log the data came from Redis cache
        return productRepository.findById(id);
    }

    // No caching on create — the product is new so nothing to cache yet
    public Product createProduct(Product product) {
        log.info("Creating product: {}", product.getName());
        return productRepository.save(product);
    }

    // @CachePut always runs the method AND updates the cache
    // This keeps the cache in sync after an update
    // Without this the cache would still have the old product data
    // and GET /api/products/1 would return stale information
    @CachePut(value = "products", key = "#id")
    public Optional<Product> updateProduct(Long id, Product updatedProduct) {
        log.info("Updating product with id: {}", id);
        return productRepository.findById(id).map(existingProduct -> {
            existingProduct.setName(updatedProduct.getName());
            existingProduct.setDescription(updatedProduct.getDescription());
            existingProduct.setPrice(updatedProduct.getPrice());
            existingProduct.setStock(updatedProduct.getStock());
            return productRepository.save(existingProduct);
        });
    }

    // @CacheEvict removes the entry from Redis when a product is deleted
    // Without this Redis would still return the deleted product
    // when someone calls GET /api/products/1
    @CacheEvict(value = "products", key = "#id")
    public boolean deleteProduct(Long id) {
        log.info("Deleting product with id: {}", id);
        if (productRepository.existsById(id)) {
            productRepository.deleteById(id);
            return true;
        }
        return false;
    }

    public List<Product> getProductsByMaxPrice(Double maxPrice) {
        log.info("Fetching products with price <= {}", maxPrice);
        return productRepository.findByPriceLessThanEqual(maxPrice);
    }

    public List<Product> getInStockProducts() {
        log.info("Fetching in-stock products");
        return productRepository.findByStockGreaterThan(0);
    }

}