package com.dockyard.springdockerapp.service;

import com.dockyard.springdockerapp.entity.Product;
import com.dockyard.springdockerapp.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * ProductService.java
 *
 * Service layer containing the business logic for products.
 * The controller calls this class, this class calls the repository.
 * This separation keeps business logic out of the controller
 * and database logic out of the service.
 *
 * @Slf4j generates a logger field called "log" automatically
 * We use it to log what the service is doing — visible in docker logs
 *
 * @RequiredArgsConstructor generates a constructor for all final fields
 * Spring uses this constructor to inject the ProductRepository dependency
 * This is constructor injection — the recommended way in Spring Boot
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ProductService {

    // Spring injects this automatically via the constructor generated by @RequiredArgsConstructor
    private final ProductRepository productRepository;

    // Get all products from the database
    public List<Product> getAllProducts() {
        log.info("Fetching all products");
        return productRepository.findAll();
    }

    // Find a single product by its ID
    // Returns Optional — the caller must handle the case where it does not exist
    public Optional<Product> getProductById(Long id) {
        log.info("Fetching product with id: {}", id);
        return productRepository.findById(id);
    }

    // Create a new product and save it to the database
    // save() in JpaRepository does INSERT if no ID is set
    public Product createProduct(Product product) {
        log.info("Creating product: {}", product.getName());
        return productRepository.save(product);
    }

    // Update an existing product
    // save() in JpaRepository does UPDATE if an ID is already set
    public Optional<Product> updateProduct(Long id, Product updatedProduct) {
        log.info("Updating product with id: {}", id);

        // First check if the product exists
        return productRepository.findById(id).map(existingProduct -> {
            // Update each field with the new values
            existingProduct.setName(updatedProduct.getName());
            existingProduct.setDescription(updatedProduct.getDescription());
            existingProduct.setPrice(updatedProduct.getPrice());
            existingProduct.setStock(updatedProduct.getStock());
            // Save and return the updated product
            return productRepository.save(existingProduct);
        });
    }

    // Delete a product by ID
    // Returns true if deleted, false if product was not found
    public boolean deleteProduct(Long id) {
        log.info("Deleting product with id: {}", id);
        if (productRepository.existsById(id)) {
            productRepository.deleteById(id);
            return true;
        }
        return false;
    }

    // Get all products under a given price
    public List<Product> getProductsByMaxPrice(Double maxPrice) {
        log.info("Fetching products with price <= {}", maxPrice);
        return productRepository.findByPriceLessThanEqual(maxPrice);
    }

    // Get all products that are in stock
    public List<Product> getInStockProducts() {
        log.info("Fetching in-stock products");
        return productRepository.findByStockGreaterThan(0);
    }
}